# Generated by Django 4.0.4 on 2022-09-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img'),
        ),
    ]
