# Generated by Django 3.2.9 on 2022-10-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Department',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='result_level',
            field=models.BigIntegerField(default=100),
        ),
    ]
