# Generated by Django 4.0.4 on 2022-07-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='file',
            new_name='file_uploaded',
        ),
    ]
