# Generated by Django 4.0.4 on 2022-08-05 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resapp', '0002_rename_file_activity_file_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
