# Generated by Django 3.2.9 on 2022-10-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resapp', '0003_alter_activity_result_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Department',
            field=models.CharField(choices=[('PET', 'PET'), ('CHEM', 'CHEM'), ('MECH', 'MECH')], default='', max_length=200),
        ),
    ]
