# Generated by Django 4.0.4 on 2022-08-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resapp', '0003_activity_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date_added']},
        ),
    ]
