# Generated by Django 3.2.9 on 2022-10-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resapp', '0004_alter_activity_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='session',
            field=models.CharField(default='', max_length=10),
        ),
    ]
