# Generated by Django 3.2.9 on 2022-10-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resapp', '0005_activity_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='session',
            field=models.CharField(choices=[('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023')], default='', max_length=10),
        ),
    ]
