# Generated by Django 4.0.4 on 2022-09-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resapp', '0005_askedquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askedquestions',
            name='user',
        ),
    ]
