# Generated by Django 3.2.9 on 2022-10-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resapp', '0006_alter_activity_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='semester',
            field=models.CharField(choices=[('Rain', 'Rain'), ('Harmattan', 'Harmattan')], default='', max_length=10),
        ),
    ]
